services:
  - type: web
    name: file-store-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: BOT_URL
        sync: false
        
